services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: ["bash", "entrypoint.sh"]
    command: uvicorn src.main:app --host=0.0.0.0 --workers 4
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_HOST
      - SECRET_KEY
    depends_on:
#      db:
#        condition: service_healthy
#      elasticsearch:
#        condition: service_healthy
    restart: unless-stopped

#  db:
#    image: postgres:16-alpine
#    environment:
#      - POSTGRES_USER
#      - POSTGRES_PASSWORD
#      - POSTGRES_DB
#      - POSTGRES_PORT
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata-volume:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-q", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#    restart: unless-stopped
#
#  redis:
#    image: redis:latest
#    environment:
#      - REDIS_PASSWORD
#      - REDIS_USER
#      - REDIS_USER_PASSWORD
#    ports:
#      - "6379:6379"
#    volumes:
#      - redisdata:/data
#    command: >
#      sh -c '
#        mkdir -p /usr/local/etc/redis &&
#        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
#        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
#        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
#        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
#        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
#        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
#        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
#      '
#    healthcheck:
#      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: unless-stopped
#
#  elasticsearch:
#    image: elasticsearch:8.15.3
#    volumes:
#      - ./elastic_config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - esdata:/usr/share/elasticsearch/data
#    environment:
#      - ES_JAVA_OPTS=-Xmx512m -Xms512m
#      - ELASTIC_PASSWORD
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    healthcheck:
#      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
#      interval: 10s
#      timeout: 10s
#      retries: 5
#
#volumes:
#    esdata:
#    pgdata-volume:
#    redisdata:
