services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000" # for DEBUG=off
      - "5678:5678" # for DEBUG=debugpy
      - "5555:5555" # for DEBUG=web-pdb
    volumes:
      - .:/src
    env_file: .env
    environment:
      - DEBUG=debugpy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PORT=5432
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:16-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
