FROM python:3.12-slim

WORKDIR /src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./poetry.lock /src/poetry.lock
COPY ./pyproject.toml /src/pyproject.toml

RUN pip install poetry
RUN poetry install --with dev

COPY . /src/
