[tool.poetry]
name = "benefits-cafeteria-backend"
version = "0.1.0"
description = "Backend part of UDV-Benefits-Cafeteria."
authors = ["Materacl <yurchenko.stas15@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.114.0"
uvicorn = "^0.30.6"
sqlalchemy = "^2.0.34"
alembic = "^1.13.2"
asyncpg = "^0.29.0"
pydantic-settings = "^2.5.0"


[tool.poetry.group.dev.dependencies]
setuptools = "^74.1.2"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
