"""Models create migration

Revision ID: 1d03c0c0183c
Revises: 4e55f920409e
Create Date: 2024-09-28 14:51:55.077981

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1d03c0c0183c"
down_revision: Union[str, None] = "4e55f920409e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
