"""udv-39 final version

Revision ID: 16cc4637d0f5
Revises: ccb32cbd2dc7
Create Date: 2024-09-28 17:51:16.003935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cc4637d0f5'
down_revision: Union[str, None] = 'ccb32cbd2dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benefit_requests', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='benefit_status_enum', native_enum=False),
               existing_nullable=False)
    op.add_column('benefits', sa.Column('is_fixed_period', sa.Boolean(), nullable=True))
    op.drop_column('benefits', 'usage_limit_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefits', sa.Column('usage_limit_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_column('benefits', 'is_fixed_period')
    op.alter_column('benefit_requests', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='benefit_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
