name: Dev Deploy
on:
  push:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: UDV-Benefits-Cafeteria/benefits-cafeteria-backend/.github/workflows/tests.yml@dev
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: StalinidzeCorp/ycr-push@main
        env:
          KEY_JSON: ${{secrets.KEY_JSON}}
          REGISTRY_ID: crpp7grglk5oa2671pne
          DOCKERFILE_PATH: ./Dockerfile.prod
          IMAGE_NAME: udb-back
          IMAGE_TAG: latest
