name: fastapi-github-actions-test

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
      - '!dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install libs
        run: poetry install --with dev

      - name: flake8
        run: poetry run flake8

      - name: black
        run: poetry run black . --check

      - name: isort
        run: poetry run isort . --check --diff

      - name: Run tests
        run: poetry run pytest tests/
