name: Tests
on:
  workflow_call:


  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
      - '!dev'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        env:
          REDIS_PASSWORD: rpass
          REDIS_USER: ruser
          REDIS_USER_PASSWORD: ruserpass
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Create env file
        run: |
          touch .env
          echo DEBUG=True >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=postgres >> .env
          echo POSTGRES_DB=postgres >> .env
          echo POSTGRES_HOST=localhost >> .env
          echo REDIS_PASSWORD=rpass >> .env
          echo REDIS_USER=ruser >> .env
          echo REDIS_USER_PASSWORD=ruserpass >> .env
          echo REDIS_HOST=localhost >> .env

      - name: Run Redis configuration
        run: |
          until docker exec $(docker ps -qf "ancestor=redis") redis-cli ping; do
            echo "Waiting for Redis to be ready..."
            sleep 5
          done
          docker exec $(docker ps -qf "ancestor=redis") sh -c '
            mkdir -p /usr/local/etc/redis &&
            echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
            echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
            echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
            echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
            echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
            echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
            redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
          '

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install libs
        run: poetry install --with dev

      - name: Create Alembic versions directory
        run: |
          mkdir -p alembic/versions
          chmod -R 777 alembic/versions

      - name: Init migrations
        run: poetry run alembic upgrade head

      - name: Create migrations
        run: poetry run alembic revision --autogenerate

      - name: Applying migrations
        run: poetry run alembic upgrade head

      - name: Run tests
        run: poetry run pytest tests/
