name: Tests
on:
  workflow_call:


  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
      - '!dev'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        container_name: db
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Create env file
        run: |
          touch .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=postgres >> .env
          echo POSTGRES_DB=postgres >> .env
          echo POSTGRES_HOST=db >> .env

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install libs
        run: poetry install --with dev

      - name: Run tests
        run: poetry run pytest tests/
